apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fashora-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev

images:
  - name: ujjawalboss/fashora-backend
    newTag: main-abc1234
  - name: ujjawalboss/fashora-frontend
    newTag: main-abc1234

patches:
  - target:
      kind: Deployment
      name: fashora-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"

  - target:
      kind: Deployment
      name: fashora-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: fashora-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

  - target:
      kind: Ingress
      name: fashora-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.fashora.yourdomain.com