apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fashora-secrets
  namespace: fashora-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dev-aws-secretsmanager  # Points to the prefixed name
    kind: SecretStore
  target:
    name: fashora-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: fashora/prod  # You can use the name or the full ARN here
