apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fashora-secrets
  namespace: fashora-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: fashora-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: fashora/prod
        property: db-password

    - secretKey: jwt-secret
      remoteRef:
        key: fashora/prod
        property: jwt-secret

    - secretKey: db-root-password
      remoteRef:
        key: fashora/prod
        property: db-root-password
